/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/p-about_us`; params?: Router.UnknownInputParams; } | { pathname: `/p-account_settings`; params?: Router.UnknownInputParams; } | { pathname: `/p-analysis_result`; params?: Router.UnknownInputParams; } | { pathname: `/p-illustration_select`; params?: Router.UnknownInputParams; } | { pathname: `/p-notification_settings`; params?: Router.UnknownInputParams; } | { pathname: `/p-reading_view`; params?: Router.UnknownInputParams; } | { pathname: `/p-work_edit`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/p-new_work` | `/p-new_work`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/p-settings` | `/p-settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/p-works_list` | `/p-works_list`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/p-about_us`; params?: Router.UnknownOutputParams; } | { pathname: `/p-account_settings`; params?: Router.UnknownOutputParams; } | { pathname: `/p-analysis_result`; params?: Router.UnknownOutputParams; } | { pathname: `/p-illustration_select`; params?: Router.UnknownOutputParams; } | { pathname: `/p-notification_settings`; params?: Router.UnknownOutputParams; } | { pathname: `/p-reading_view`; params?: Router.UnknownOutputParams; } | { pathname: `/p-work_edit`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/p-new_work` | `/p-new_work`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/p-settings` | `/p-settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/p-works_list` | `/p-works_list`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/p-about_us${`?${string}` | `#${string}` | ''}` | `/p-account_settings${`?${string}` | `#${string}` | ''}` | `/p-analysis_result${`?${string}` | `#${string}` | ''}` | `/p-illustration_select${`?${string}` | `#${string}` | ''}` | `/p-notification_settings${`?${string}` | `#${string}` | ''}` | `/p-reading_view${`?${string}` | `#${string}` | ''}` | `/p-work_edit${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/p-new_work${`?${string}` | `#${string}` | ''}` | `/p-new_work${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/p-settings${`?${string}` | `#${string}` | ''}` | `/p-settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/p-works_list${`?${string}` | `#${string}` | ''}` | `/p-works_list${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/p-about_us`; params?: Router.UnknownInputParams; } | { pathname: `/p-account_settings`; params?: Router.UnknownInputParams; } | { pathname: `/p-analysis_result`; params?: Router.UnknownInputParams; } | { pathname: `/p-illustration_select`; params?: Router.UnknownInputParams; } | { pathname: `/p-notification_settings`; params?: Router.UnknownInputParams; } | { pathname: `/p-reading_view`; params?: Router.UnknownInputParams; } | { pathname: `/p-work_edit`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/p-new_work` | `/p-new_work`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/p-settings` | `/p-settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/p-works_list` | `/p-works_list`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
